### ISSUE TITLE
Hydration Error

### ISSUE THREAD

**Issue by Twilight876** [Aditya61101/teams-chat-app#1]
it gives multiple errors 
![ScreenShot Tool -20240614145733](https://github.com/Aditya61101/teams-chat-app/assets/114775780/ff5a50cd-8c88-4d06-9779-e61f1f3ce8dd)
![ScreenShot Tool -20240614145702](https://github.com/Aditya61101/teams-chat-app/assets/114775780/f261968c-d33d-46f7-b66e-70966147bb53)

**Comment by Aditya61101** [comment]
Hi @Twilight876 , if you want to solve this issue you can but make sure to commit any changes to a new branch and raise a PR from it only.

**Comment by Twilight876** [comment]
i solved this i have another issue with database
![ScreenShot Tool -20240614145733](https://github.com/Aditya61101/teams-chat-app/assets/114775780/eff77cdf-e4a9-4b88-abd5-db197b8f75dc)

**Comment by Twilight876** [comment]
i solved it i have another issue with db
![ScreenShot Tool -20240614155521](https://github.com/Aditya61101/teams-chat-app/assets/114775780/a47628dd-c9f2-49df-9ec4-1172e9d17063)

**Comment by Twilight876** [comment]
and i modified .env file and added the link of MangoDB Atlas

**Comment by Twilight876** [comment]
and clerk and livekit i modified everything

**Comment by Twilight876** [comment]
can you please tell me steps to solve proplem
