### ISSUE TITLE
MongoDB url

### ISSUE THREAD

**Issue by Twilight876** [Aditya61101/teams-chat-app#2]
This error please 
![ScreenShot Tool -20240614190302](https://github.com/Aditya61101/teams-chat-app/assets/114775780/8fa56093-f670-4858-abd8-a67ce98216a4)

**Comment by Aditya61101** [comment]
Will give u the .env credentials tomorrow morning.

**Comment by Aditya61101** [comment]
hi @Twilight876 , this is the mongoDB url: DATABASE_URL="mongodb+srv://adi_tya:5lU6VsSKsQdfQZPF@chat-cluster.hp9jpxv.mongodb.net/Chat?retryWrites=true&w=majority"

**Comment by Aditya61101** [comment]
please fork the repo before committing any new changes

**Comment by Aditya61101** [comment]
btw @Twilight876 , where are u from?

**Comment by Twilight876** [comment]
Sprey fpr late replays i am from egypt but now i am in US I got api of UploadThing and added them in .env but when i click upload it doesn't upload

**Comment by Twilight876** [comment]
Please help me

**Comment by Twilight876** [comment]
i thinks there is problem with my UploadThing api
![ScreenShot Tool -20240615223514](https://github.com/Aditya61101/teams-chat-app/assets/114775780/e72a13b9-544d-4f2c-bbf2-ff21a06cbeb4)
